{
 "title": "LeemanDB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_global_status_uptime" }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[$__interval]) or irate(mysql_global_status_queries[5m])"
    }
   ]
  },
  {
   "title": "Buffer Pool Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received[$__interval]) or irate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent[$__interval]) or irate(mysql_global_status_bytes_sent[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Network Usage Per HOUR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(mysql_global_status_bytes_received[60m])",
     "legendFormat": "Received"
    },
    {
     "expr": "increase(mysql_global_status_bytes_sent[60m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Client Threads Activity",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "max_over_time(mysql_global_status_threads_connected[5m])",
     "legendFormat": "Threads Connected"
    },
    {
     "expr": "max_over_time(mysql_global_status_threads_running[5m])",
     "legendFormat": "Threads Running"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Table Open Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 1, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits[5m]) or rate(mysql_global_status_table_open_cache_hits[$__interval]))\r\n/ ((rate(mysql_global_status_table_open_cache_hits[5m]) or rate(mysql_global_status_table_open_cache_hits[$__interval]))\r\n+ (rate(mysql_global_status_table_open_cache_misses[5m]) or rate(mysql_global_status_table_open_cache_misses[$__interval])))",
     "legendFormat": "Table opens hit ratio"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits[$__interval]) or irate(mysql_global_status_table_open_cache_hits[5m])",
     "legendFormat": "Table open cache hits"
    }
   ]
  },
  {
   "title": "Buffer Pool Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_reads",
     "legendFormat": "Bufffer Pool Reads"
    },
    {
     "expr": "mysql_global_status_innodb_buffer_pool_read_requests",
     "legendFormat": "Bufffer Pool Read Requests"
    }
   ]
  },
  {
   "title": "Buffer Pool Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mysql_global_status_innodb_buffer_pool_read_requests - mysql_global_status_innodb_buffer_pool_reads) /mysql_global_status_innodb_buffer_pool_read_requests"
    }
   ]
  },
  {
   "title": "Buffer pool Utlization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(sum(mysql_global_status_buffer_pool_pages) by (instance) - sum(mysql_global_status_buffer_pool_pages{state=\"free\"}) by (instance)) / sum(mysql_global_status_buffer_pool_pages) by (instance)",
     "legendFormat": "Buffer Pool Utilization Rate"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received[60m]) or irate(mysql_global_status_bytes_received[60m])",
     "legendFormat": "Bytes Received (1hr)"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent[60m]) or irate(mysql_global_status_bytes_sent[60m])",
     "legendFormat": "Bytes Sent (1hr)"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_slow_queries)",
     "legendFormat": "Total of Slow Queries"
    },
    {
     "expr": "rate(mysql_global_status_slow_queries[10m])",
     "legendFormat": "Slow Query Rate"
    }
   ]
  },
  { "title": "MySQL Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Aborted Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 3, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_aborted_connects[$__interval]) or irate(mysql_global_status_aborted_connects[5m])",
     "legendFormat": "Aborted Connects"
    },
    {
     "expr": "rate(mysql_global_status_aborted_clients[$__interval]) or irate(mysql_global_status_aborted_clients[5m])",
     "legendFormat": "Timeout Clients"
    }
   ]
  },
  {
   "title": "MySQL Connection Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_max_connections",
     "legendFormat": "Total Available Connection"
    },
    {
     "expr": "mysql_global_variables_max_connections - mysql_global_status_threads_connected",
     "legendFormat": "Remaining available connections"
    },
    {
     "expr": "mysql_global_status_aborted_connects",
     "legendFormat": "Aborted or suspended connections"
    }
   ]
  },
  {
   "title": "MySQL Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_connection_errors_total)",
     "legendFormat": "Total of Errors"
    },
    {
     "expr": "mysql_global_status_connection_errors_total{error=\"select\"}",
     "legendFormat": "Queries Errors"
    },
    {
     "expr": "mysql_global_status_connection_errors_total{error=\"internal\"}",
     "legendFormat": "Internal Errors"
    }
   ]
  },
  { "title": "MySQL Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Select Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_select_scan[$__interval]) or irate(mysql_global_status_select_scan[5m])",
     "legendFormat": "Select Scan"
    },
    {
     "expr": "rate(mysql_global_status_select_full_join[$__interval]) or irate(mysql_global_status_select_full_join[5m])",
     "legendFormat": "Select Full Join"
    },
    {
     "expr": "rate(mysql_global_status_select_full_range_join[$__interval]) or irate(mysql_global_status_select_full_range_join[5m])",
     "legendFormat": "Select Full Range Join"
    }
   ]
  },
  {
   "title": "MySQL Questions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions[5m])",
     "legendFormat": "Questions"
    }
   ]
  },
  {
   "title": "MySQL Query Rate (1min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Query Cache Free memory",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_qcache_free_memory{instance=\"10.224.96.34:9104\"}"
    }
   ]
  },
  {
   "title": " MySQL Command Rate (1min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=~\"select|insert\"}[1m])) without (command)",
     "legendFormat": "Select/Insert"
    },
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=~\"delete|update\"}[1m])) without (command)",
     "legendFormat": "{{label_name}} delete/Update"
    }
   ]
  },
  {
   "title": "MySQL Command/Queries (1min)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=~\"insert|update|delete|select\"}[1m]))",
     "legendFormat": "Commands"
    },
    {
     "expr": "sum(rate(mysql_global_status_queries[5m]))",
     "legendFormat": "Queries"
    }
   ]
  }
 ]
}